#!/opt/cleanpython26/bin/python /opt/zaamdashboard/bin/py

import ZEO
import os
import sys

users = '/home/databases/zopeorgkeyupload/zope.org-users'

def main(args=None):
    if args is None:
        args = sys.argv[1:]
    login = args.pop(0)

    conn = ZEO.connection(8200, read_only=True)
    try:
        conn.root.zaam_users.getIdByLogin(login, 'svn.zope.org')
    except KeyError:
        print 'Invalid user'
        print login
        sys.exit(1)

    name = ' '.join(args)
    if os.spawnl(os.P_WAIT, '/usr/sbin/useradd', '/usr/sbin/useradd',
                 '-G', 'cvsusers,zopesvn', '-c', name, login):
        print 'useradd failed'
    else:
        open(users, 'a').write(login+'\n')

if __name__ == '__main__':
    main()
